SELECT 
    SUM(SCORE) AS SCORE, 
    EMP_NO, 
    EMP_NAME, 
    POSITION, 
    EMAIL
FROM 
    HR_DEPARTMENT 
JOIN 
    HR_EMPLOYEES USING (DEPT_ID)
JOIN 
    HR_GRADE USING (EMP_NO)
GROUP BY 
    EMP_NO, EMP_NAME, POSITION, EMAIL
ORDER BY 
    SCORE DESC
LIMIT 1;
