SELECT
    j.YEAR,
    j.MSOC - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN (
    SELECT
        MAX(SIZE_OF_COLONY) AS MSOC,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) j
    ON YEAR(e.DIFFERENTIATION_DATE) = j.YEAR
ORDER BY
    j.YEAR ASC,
    YEAR_DEV ASC;
